import type { Language } from '../types/qissa'

export type I18nKey =
  | 'app.title' | 'nav.welcome' | 'nav.onboarding' | 'nav.home'
  | 'welcome.title' | 'welcome.subtitle' | 'welcome.cta' | 'welcome.tagline' | 'welcome.explanation'
  | 'actions.next' | 'actions.back' | 'actions.start_story' | 'actions.continue' | 'actions.save'
  | 'onboarding.title' | 'onboarding.age' | 'onboarding.language' | 'onboarding.hero' | 'onboarding.world' | 'onboarding.story_mode' | 'onboarding.mood' | 'onboarding.world_hint' | 'onboarding.world_continue'
  | 'home.title' | 'home.continue_story' | 'home.ready' | 'home.create_first_series' | 'home.next_create_series'
  | 'age.3_5' | 'age.6_8' | 'age.9_10'
  | 'language.ru' | 'language.uz' | 'language.kz'
  | 'hero.girl_hero' | 'hero.boy_hero' | 'hero.animal' | 'hero.magical_hero' | 'hero.custom' | 'hero.custom_placeholder'
  | 'mode.series' | 'mode.one_time'
  | 'mood.bedtime' | 'mood.kind_adventure'
  | 'story.read_mode' | 'story.listen_mode' | 'story.listen_placeholder' | 'story.audio_controls' | 'story.make_choice' | 'story.words_preview' | 'story.choice_confirmation'
  | 'story.world_remembers' | 'story.continue_next_episode' | 'story.next_episode_hint' | 'story.episode_end_title' | 'story.episode_end_body' | 'story.back_home' | 'story.confirm_choice' | 'story.narrative_title'
  | 'story.preview_helper' | 'story.show_words' | 'story.hide_words' | 'story.return_home' | 'story.choice_saved_title' | 'story.opening_next_episode' | 'story.end_state_title' | 'story.end_state_body' | 'story.one_time_final_title' | 'story.one_time_final_body' | 'story.series_final_title' | 'story.series_final_body' | 'story.start_new_story' | 'story.read_again' | 'story.back_to_final'
  | 'home.world_remembers' | 'home.last_episode_summary' | 'home.reset_story' | 'home.restart_story' | 'home.story_completed_title' | 'home.story_completed_body' | 'home.reopen_story'
  | 'home.show_details' | 'home.hide_details' | 'home.edit_setup' | 'home.start_one_time' | 'home.start_new_story' | 'home.reset_story_soft' | 'home.reset_progress_hint' | 'home.one_time_in_progress' | 'home.one_time_completed_body' | 'home.series_completed_title' | 'home.one_time_completed_title'
  | 'reader.open_settings' | 'reader.close_settings' | 'reader.text_size' | 'reader.font' | 'reader.line_spacing' | 'reader.theme'
  | 'reader.text_size.small' | 'reader.text_size.medium' | 'reader.text_size.large' | 'reader.text_size.extra_large'
  | 'reader.theme.light' | 'reader.theme.warm' | 'reader.theme.night'
  | 'reader.font.standard' | 'reader.font.soft' | 'reader.font.dyslexia_friendly'
  | 'reader.line_spacing.normal' | 'reader.line_spacing.relaxed' | 'reader.line_spacing.wide'
  | 'listen.change_voice' | 'listen.play' | 'listen.pause' | 'listen.back_10' | 'listen.forward_10' | 'listen.speed' | 'listen.progress'
  | 'voice.soft_female' | 'voice.calm_male' | 'voice.neutral_storyteller' | 'voice.cheerful_daytime'

export type I18nDictionary = Record<I18nKey, string>

const ru: I18nDictionary = {
'app.title':'QISSA','nav.welcome':'Приветствие','nav.onboarding':'Онбординг','nav.home':'Главная',
'welcome.title':'QISSA','welcome.subtitle':'Тёплые персональные сказки для семьи.','welcome.cta':'Начать сказку','welcome.tagline':'Добрые сказки, которые продолжаются каждый день.','welcome.explanation':'Создайте первую сказку. Ребёнок сделает выбор, а мир истории запомнит его.',
'actions.next':'Далее','actions.back':'Назад','actions.start_story':'Начать сказку','actions.continue':'Продолжить','actions.save':'Сохранить',
'onboarding.title':'Быстрый старт','onboarding.age':'Для какого возраста сказка?','onboarding.language':'На каком языке рассказать сказку?','onboarding.hero':'Кто будет главным героем?','onboarding.world':'Где начнётся история?','onboarding.story_mode':'Какой формат сказки выбрать?','onboarding.mood':'Какую сказку создать?','onboarding.world_hint':'Выберите мир и продолжите.','onboarding.world_continue':'Выбрать этот мир',
'home.title':'Дом историй','home.continue_story':'Продолжить историю','home.ready':'Ваш сказочный мир готов.','home.create_first_series':'Создать первую серию','home.next_create_series':'Следующий шаг: создать первую серию',
'age.3_5':'3–5 лет','age.6_8':'6–8 лет','age.9_10':'9–10 лет',
'language.ru':'Русский','language.uz':'O‘zbekcha','language.kz':'Қазақша',
'hero.girl_hero':'Девочка-герой','hero.boy_hero':'Мальчик-герой','hero.animal':'Животное','hero.magical_hero':'Волшебный герой','hero.custom':'Свой герой','hero.custom_placeholder':'Например: маленький барс, Лола, Амир, добрый робот',
'mode.series':'Сказочный сериал','mode.one_time':'Разовая сказка',
'mood.bedtime':'Перед сном','mood.kind_adventure':'Доброе приключение',

'reader.open_settings':'Настройки чтения','reader.close_settings':'Закрыть','reader.text_size':'Размер текста','reader.font':'Шрифт','reader.line_spacing':'Интервал строк','reader.theme':'Тема',
'reader.text_size.small':'Маленький','reader.text_size.medium':'Средний','reader.text_size.large':'Крупный','reader.text_size.extra_large':'Очень крупный',
'reader.theme.light':'Светлая','reader.theme.warm':'Тёплая','reader.theme.night':'Ночная',
'reader.font.standard':'Стандартный','reader.font.soft':'Мягкий','reader.font.dyslexia_friendly':'Читаемый',
'reader.line_spacing.normal':'Обычный','reader.line_spacing.relaxed':'Свободный','reader.line_spacing.wide':'Широкий',
'listen.change_voice':'Голос рассказчика','listen.play':'▶ Пуск','listen.pause':'⏸ Пауза','listen.back_10':'−10 сек','listen.forward_10':'+10 сек','listen.speed':'Скорость','listen.progress':'Прогресс',
'voice.soft_female':'Мягкий женский','voice.calm_male':'Спокойный мужской','voice.neutral_storyteller':'Нейтральный рассказчик','voice.cheerful_daytime':'Бодрый дневной',
'story.read_mode':'Читать','story.listen_mode':'Слушать','story.listen_placeholder':'Здесь будет спокойное прослушивание с обложкой эпизода и управлением аудио.','story.audio_controls':'Управление аудио','story.make_choice':'Что выберет герой?','story.words_preview':'Слова из истории (по желанию)','story.choice_confirmation':'Выбор принят.','story.world_remembers':'История запомнила ваш выбор.','story.continue_next_episode':'Продолжить следующую серию','story.next_episode_hint':'Следующая серия начнётся с этого.','story.episode_end_title':'Финал демо-эпизода','story.episode_end_body':'Спасибо, что дочитали. Можно вернуться домой и начать новую историю.','story.back_home':'Домой','story.confirm_choice':'Подтвердить выбор','story.narrative_title':'Сказка','story.preview_helper':'Выберите вариант и посмотрите, как изменится путь.','story.show_words':'Показать слова из сказки','story.hide_words':'Скрыть слова','story.return_home':'Вернуться домой','story.choice_saved_title':'История запомнила ваш выбор.','story.opening_next_episode':'Открываем следующую серию…','story.end_state_title':'Спокойный финал демо','story.end_state_body':'Спасибо за чтение. Можно вернуться домой и начать новую историю.','story.one_time_final_title':'Сказка завершена','story.one_time_final_body':'Эта история мягко завершилась. Можно открыть её снова или начать новую.','story.series_final_title':'Серия завершена','story.series_final_body':'Это конец текущей демо-серии. Спасибо, что были с нами.','story.start_new_story':'Начать новую сказку','story.read_again':'Прочитать снова','story.back_to_final':'Вернуться к финалу','home.world_remembers':'История помнит ваш выбор.','home.last_episode_summary':'Чем закончилась последняя серия','home.reset_story':'Сбросить историю','home.restart_story':'Если хотите, можно начать историю заново','home.story_completed_title':'Демо-история завершена','home.story_completed_body':'Вы можете открыть историю снова или начать новую с нуля.','home.reopen_story':'Открыть текущую историю','home.show_details':'Показать детали','home.hide_details':'Скрыть детали','home.edit_setup':'Изменить настройки','home.start_one_time':'Начать отдельную сказку','home.start_new_story':'Начать новую сказку','home.reset_story_soft':'Сбросить только прогресс истории','home.reset_progress_hint':'Можно мягко начать заново: настройки и язык сохранятся.','home.one_time_in_progress':'Это отдельная сказка — можно спокойно продолжить.','home.one_time_completed_body':'Эта отдельная сказка завершена. Можно начать новую.','home.series_completed_title':'Демо-серия завершена','home.one_time_completed_title':'Сказка завершена',
}
const uz: I18nDictionary = { ...ru,
'nav.welcome':'Xush kelibsiz','nav.onboarding':'Boshlash','nav.home':'Bosh sahifa',
'welcome.subtitle':'Oilalar uchun iliq shaxsiy ertaklar.','welcome.cta':'Ertakni boshlash','welcome.tagline':'Har kuni davom etadigan mehribon ertaklar.','welcome.explanation':'Birinchi ertakni yarating. Bola tanlov qiladi, hikoya olami esa uni eslab qoladi.',
'actions.next':'Keyingi','actions.back':'Orqaga','actions.start_story':'Ertakni boshlash','actions.continue':'Davom etish','actions.save':'Saqlash',
'onboarding.title':'Tez boshlash','onboarding.age':'Ertak qaysi yosh uchun?','onboarding.language':'Ertak qaysi tilda bo‘lsin?','onboarding.hero':'Asosiy qahramon kim bo‘ladi?','onboarding.world':'Hikoya qayerda boshlanadi?','onboarding.story_mode':'Qaysi hikoya formatini tanlaysiz?','onboarding.mood':'Qanday ertak yaratamiz?',
'home.title':'Hikoyalar uyi','home.continue_story':'Hikoyani davom ettirish','home.ready':'Sizning ertak olamingiz tayyor.','home.create_first_series':'Birinchi qismni yaratish','home.next_create_series':'Keyingi qadam: birinchi qismni yaratish',
'age.3_5':'3–5 yosh','age.6_8':'6–8 yosh','age.9_10':'9–10 yosh',
'language.ru':'Ruscha','language.uz':'O‘zbekcha','language.kz':'Qozoqcha',
'hero.girl_hero':'Qiz qahramon','hero.boy_hero':'O‘g‘il qahramon','hero.animal':'Jonivor','hero.magical_hero':'Sehrli qahramon','hero.custom':'O‘z qahramoningiz','hero.custom_placeholder':'Masalan: kichik bars, Lola, Amir, mehribon robot',
'mode.series':'Ertak seriali','mode.one_time':'Bir martalik ertak',
'mood.bedtime':'Uxlashdan oldin','mood.kind_adventure':'Mehribon sarguzasht',
'reader.open_settings':'O‘qish sozlamalari','reader.close_settings':'Yopish','reader.text_size':'Matn hajmi','reader.font':'Shrift','reader.line_spacing':'Qator oralig‘i','reader.theme':'Mavzu',
'reader.text_size.small':'Kichik','reader.text_size.medium':'O‘rta','reader.text_size.large':'Katta','reader.text_size.extra_large':'Juda katta',
'reader.theme.light':'Yorug‘','reader.theme.warm':'Iliq','reader.theme.night':'Tungi',
'reader.font.standard':'Standart','reader.font.soft':'Yumshoq','reader.font.dyslexia_friendly':'O‘qishga qulay',
'reader.line_spacing.normal':'Oddiy','reader.line_spacing.relaxed':'Erkin','reader.line_spacing.wide':'Keng',
'listen.change_voice':'Rivoyatchi ovozi','listen.play':'▶ Boshlash','listen.pause':'⏸ Pauza','listen.back_10':'−10 soniya','listen.forward_10':'+10 soniya','listen.speed':'Tezlik','listen.progress':'Jarayon',
'voice.soft_female':'Yumshoq ayol ovozi','voice.calm_male':'Sokin erkak ovozi','voice.neutral_storyteller':'Neytral rivoyatchi','voice.cheerful_daytime':'Quvnoq kunduzgi',
'story.read_mode':'O‘qish','story.listen_mode':'Tinglash','story.listen_placeholder':'Bu yerda epizod muqovasi va audio boshqaruvi ko‘rinadi.','story.audio_controls':'Audio boshqaruvi','story.make_choice':'Qahramon nimani tanlaydi?','story.words_preview':'Hikoyadagi so‘zlar (ixtiyoriy)','story.choice_confirmation':'Tanlov qabul qilindi.','story.world_remembers':'Hikoya olami tanlovingizni eslab qoldi.','story.continue_next_episode':'Keyingi qismga o‘tish','story.next_episode_hint':'Keyingi qism shu tanlovdan boshlanadi.','story.episode_end_title':'Hikoya davom etadi.','story.episode_end_body':'Hikoya olami bu qismda nima bo‘lganini eslab qoladi.','story.back_home':'Bosh sahifaga qaytish','story.confirm_choice':'Tanlovni tasdiqlash','story.narrative_title':'Ertak sahifasi','home.world_remembers':'Hikoya olami tanlovingizni eslaydi.','home.last_episode_summary':'Oxirgi qism yakuni','home.reset_story':'Hikoyani qayta boshlash','home.restart_story':'Istasangiz, hikoyani boshidan boshlashingiz mumkin','home.story_completed_title':'Demo-hikoya yakunlandi','home.story_completed_body':'Hikoyani yana ochishingiz yoki boshidan boshlashingiz mumkin.','home.reopen_story':'Joriy hikoyani ochish','home.show_details':'Batafsil ko‘rsatish','home.hide_details':'Batafsilni yopish','home.edit_setup':'Sozlamani o‘zgartirish','home.start_one_time':'Alohida ertakni boshlash','home.start_new_story':'Yangi ertakni boshlash','home.reset_story_soft':'Faqat hikoya jarayonini tozalash','home.reset_progress_hint':'Istasangiz, hikoyani muloyim qayta boshlang: sozlamalar va til saqlanadi.','home.one_time_in_progress':'Bu alohida ertak — xotirjam davom ettiring.','home.one_time_completed_body':'Bu alohida ertak yakunlandi. Yangisini boshlashingiz mumkin.','home.series_completed_title':'Demo qism yakunlandi','home.one_time_completed_title':'Ertak yakunlandi','story.preview_helper':'Variantni tanlab, yo‘lini avval ko‘rib oling.','story.show_words':'Ertakdagi so‘zlarni ko‘rsatish','story.hide_words':'So‘zlarni yashirish','story.return_home':'Bosh sahifaga qaytish','story.choice_saved_title':'Hikoya tanlovingizni eslab qoldi.','story.opening_next_episode':'Keyingi qism ochilmoqda…','story.end_state_title':'Demoning muloyim yakuni','story.end_state_body':'O‘qiganingiz uchun rahmat. Bosh sahifaga qaytib yangi hikoya boshlashingiz mumkin.','story.one_time_final_title':'Ertak yakunlandi','story.one_time_final_body':'Bu ertak iliq yakun topdi. Uni yana ochishingiz yoki yangisini boshlashingiz mumkin.','story.series_final_title':'Qism yakunlandi','story.series_final_body':'Joriy demo qismi shu yerda tugaydi. Biz bilan bo‘lganingiz uchun rahmat.','story.start_new_story':'Yangi ertakni boshlash','story.read_again':'Yana o‘qish','story.back_to_final':'Yakun sahifasiga qaytish','onboarding.world_hint':'Bir olamni tanlang va davom eting.','onboarding.world_continue':'Shu olamni tanlash' }
const kz: I18nDictionary = { ...ru,
'nav.welcome':'Қош келдіңіз','nav.onboarding':'Бастау','nav.home':'Басты бет',
'welcome.subtitle':'Отбасына арналған жылы жеке ертегілер.','welcome.cta':'Ертегіні бастау','welcome.tagline':'Күн сайын жалғасатын мейірімді ертегілер.','welcome.explanation':'Алғашқы ертегіні жасаңыз. Бала таңдау жасайды, ал оқиға әлемі оны есте сақтайды.',
'actions.next':'Келесі','actions.back':'Артқа','actions.start_story':'Ертегіні бастау','actions.continue':'Жалғастыру','actions.save':'Сақтау',
'onboarding.title':'Жылдам бастау','onboarding.age':'Ертегі қай жасқа арналған?','onboarding.language':'Ертегі қай тілде болсын?','onboarding.hero':'Басты кейіпкер кім болады?','onboarding.world':'Оқиға қай жерде басталады?','onboarding.story_mode':'Қай ертегі форматын таңдайсыз?','onboarding.mood':'Қандай ертегі жасаймыз?',
'home.title':'Оқиғалар үйі','home.continue_story':'Оқиғаны жалғастыру','home.ready':'Сіздің ертегі әлеміңіз дайын.','home.create_first_series':'Бірінші бөлімді жасау','home.next_create_series':'Келесі қадам: бірінші бөлімді жасау',
'age.3_5':'3–5 жас','age.6_8':'6–8 жас','age.9_10':'9–10 жас',
'language.ru':'Орысша','language.uz':'Өзбекше','language.kz':'Қазақша',
'hero.girl_hero':'Қыз кейіпкер','hero.boy_hero':'Ұл кейіпкер','hero.animal':'Жануар','hero.magical_hero':'Сиқырлы кейіпкер','hero.custom':'Өз кейіпкеріңіз','hero.custom_placeholder':'Мысалы: кішкентай барыс, Лола, Әмір, мейірімді робот',
'mode.series':'Ертегі сериалы','mode.one_time':'Бір реттік ертегі',
'mood.bedtime':'Ұйықтар алдында','mood.kind_adventure':'Мейірімді шытырман',
'reader.open_settings':'Оқу баптаулары','reader.close_settings':'Жабу','reader.text_size':'Мәтін өлшемі','reader.font':'Қаріп','reader.line_spacing':'Жол аралығы','reader.theme':'Тақырып',
'reader.text_size.small':'Кіші','reader.text_size.medium':'Орташа','reader.text_size.large':'Үлкен','reader.text_size.extra_large':'Өте үлкен',
'reader.theme.light':'Жарық','reader.theme.warm':'Жылы','reader.theme.night':'Түнгі',
'reader.font.standard':'Стандарт','reader.font.soft':'Жұмсақ','reader.font.dyslexia_friendly':'Оқуға жеңіл',
'reader.line_spacing.normal':'Қалыпты','reader.line_spacing.relaxed':'Еркін','reader.line_spacing.wide':'Кең',
'listen.change_voice':'Әңгімелеуші дауысы','listen.play':'▶ Бастау','listen.pause':'⏸ Үзіліс','listen.back_10':'−10 сек','listen.forward_10':'+10 сек','listen.speed':'Жылдамдық','listen.progress':'Орындалу барысы',
'voice.soft_female':'Жұмсақ әйел дауысы','voice.calm_male':'Байсалды ер дауыс','voice.neutral_storyteller':'Бейтарап әңгімелеуші','voice.cheerful_daytime':'Көңілді күндізгі',
'story.read_mode':'Оқу','story.listen_mode':'Тыңдау','story.listen_placeholder':'Мұнда эпизод мұқабасы мен аудио басқару көрсетіледі.','story.audio_controls':'Аудио басқару','story.make_choice':'Кейіпкер нені таңдайды?','story.words_preview':'Оқиға сөздері (қалау бойынша)','story.choice_confirmation':'Таңдау қабылданды.','story.world_remembers':'Оқиға әлемі таңдауыңызды ұмытпайды.','story.continue_next_episode':'Келесі бөлімге өту','story.next_episode_hint':'Келесі бөлім осы таңдаудан басталады.','story.episode_end_title':'Оқиға жалғасады.','story.episode_end_body':'Оқиға әлемі бұл бөлімде не болғанын есте сақтайды.','story.back_home':'Басты бетке қайту','story.confirm_choice':'Таңдауды растау','story.narrative_title':'Ертегі беті','home.world_remembers':'Оқиға әлемі таңдауыңызды есте сақтайды.','home.last_episode_summary':'Соңғы бөлімнің қорытындысы','home.reset_story':'Оқиғаны қайта бастау','home.restart_story':'Қаласаңыз, оқиғаны басынан бастауға болады','home.story_completed_title':'Демо-оқиға аяқталды','home.story_completed_body':'Оқиғаны қайта ашуға немесе басынан бастауға болады.','home.reopen_story':'Ағымдағы оқиғаны ашу','home.show_details':'Толығын көру','home.hide_details':'Толығын жасыру','home.edit_setup':'Баптауды өзгерту','home.start_one_time':'Жеке ертегіні бастау','home.start_new_story':'Жаңа ертегі бастау','home.reset_story_soft':'Тек ертегі барысын тазалау','home.reset_progress_hint':'Қаласаңыз, ертегіні жұмсақ қайта бастаңыз: баптаулар мен тіл сақталады.','home.one_time_in_progress':'Бұл жеке ертегі — сабырмен жалғастырыңыз.','home.one_time_completed_body':'Бұл жеке ертегі аяқталды. Жаңасын бастауға болады.','home.series_completed_title':'Демо бөлім аяқталды','home.one_time_completed_title':'Ертегі аяқталды','story.preview_helper':'Нұсқаны таңдап, бағытын алдын ала көріңіз.','story.show_words':'Ертегідегі сөздерді көрсету','story.hide_words':'Сөздерді жасыру','story.return_home':'Басты бетке оралу','story.choice_saved_title':'Оқиға таңдауыңызды сақтады.','story.opening_next_episode':'Келесі бөлім ашылып жатыр…','story.end_state_title':'Демоның жайлы финалы','story.end_state_body':'Оқығаныңызға рақмет. Басты бетке оралып, жаңа ертегі бастауға болады.','story.one_time_final_title':'Ертегі аяқталды','story.one_time_final_body':'Бұл ертегі жылы аяқталды. Оны қайта ашуға немесе жаңасын бастауға болады.','story.series_final_title':'Бөлім аяқталды','story.series_final_body':'Ағымдағы демо бөлім осы жерде аяқталады. Бізбен болғаныңызға рақмет.','story.start_new_story':'Жаңа ертегі бастау','story.read_again':'Қайта оқу','story.back_to_final':'Финалға оралу','onboarding.world_hint':'Әлемді таңдап, жалғастырыңыз.','onboarding.world_continue':'Осы әлемді таңдау' }

export const dictionaries: Record<Language, I18nDictionary> = { ru, uz, kz }
