import type { NormalizedStoryContext } from './contracts.ts'

// Editorial quality supplements the immutable blueprint, existing deterministic
// validators and child-safety gates. Never override safety, canon or choice facts.
// No extra model call, new schema field, provider retry or length hard gate.
const isNewSeriesDebut = (context: NormalizedStoryContext): boolean =>
  context.episodeIndex === 1 &&
  (!Array.isArray(context.choiceHistory) || context.choiceHistory.length === 0) &&
  (!Array.isArray(context.recurringCharacters) || context.recurringCharacters.length === 0)

const debutArchitectGuidance = [
  'FIRST ENCOUNTER, NOT EPISODE EIGHT. Design the E1 opening so a child who has never met anyone can understand the hero without external UI context. Establish the hero as a person or creature, a simple home or ordinary starting place, and WHY the hero is in the story location today. An ordinary home detail is fictional world canon, not a claim about the real child; make only the minimum new facts needed and record any durable facts consistently in state_patch.',
  'Introduce every newly named supporting character at first appearance with an understandable role or species and an observable relationship to the hero. Explain in action how they meet or why they already know one another. Do not introduce a mysterious proper name such as Yumo as though the listener has read seven earlier episodes. Keep names, species, first-meeting facts and memory internally consistent; do not assume friendship before it is shown.',
  'In the first 40-80 words ground hero, starting place, current activity, and route or reason for being here. Within approximately 60-120 words introduce one concrete curious incident or goal. Treat these as flexible orientation budgets, not a scenery quota or a forced cold open. Give a newcomer all facts needed to follow the FIRST story; save nonessential biography for later episodes.',
].join(' ')

const debutNarratorGuidance = [
  'This is a first encounter for a new listener: do not narrate it like episode eight. In natural child-facing prose, establish who {{HERO}} is, where the hero starts and why the hero is here before asking the listener to care about an unfamiliar group. At first mention of every newly invented proper name, make the species or identity and relationship comprehensible without a character-list dump. If the blueprint lacks this orientation, use only its supported facts and ordinary transient explanation; do not invent a permanent home, prior friendship or relationship not planned by the Architect.',
  'Spend the next paragraphs on the hero doing things that affect the one central problem: attempt, result, new information, adjustment and visible consequence. An emotional expression, nod, smile, leaf-folding, nose-rubbing, reassurance or waiting does NOT count as a plot beat merely because it is observable; a humorous action counts when it changes the situation or reveals a character. Do not replace motion with static ensemble attendance. Do not pad to 380-420 words; give each paragraph causal work or return an honestly short draft for existing Repair/validation.',
].join(' ')

export const storyArchitectEditorialGuidance = (context: NormalizedStoryContext): string => [
  'Editorial story quality: keep one concrete child-scale desire or goal with a satisfying observable payoff. If the setup promises an event tonight, let the characters experience a small version of that event by tonight\'s ending; if it is genuinely tomorrow, say so in the setup and fully resolve tonight\'s separate local goal. Do not silently postpone a promise or drop an explicitly necessary missing item.',
  ...(isNewSeriesDebut(context) ? [debutArchitectGuidance] : []),
  'For a returning series, do not repeat a full origin story or overwrite established homes, friendships, locations or identities. Re-anchor briefly with relevant existing canon and prior choice consequences. Episode 2 continues the exact confirmed Episode 1 bridge rather than reintroducing the cast.',
  'Plan causal beats in which something actually changes: a character tries an action, discovers a gentle surprise, responds to a consequence, changes a relationship or finishes a child-visible step. Dialogue and listening are welcome, but do not fill most beats with repeated debate about the same action or object. Do not add unrelated danger, pursuit or a stressful cliffhanger just to create momentum.',
  'For the planned 5-7 meaningful pre-choice beats, write down the cause and resulting changed situation, not a checklist of physical motions or interchangeable feelings. At least one beat must involve an active hero attempt with a genuine result and one must yield new relevant information. A repeated smile, pause, observation or encouragement alone is not progress. Keep one central problem and no gratuitous second conflict.',
  'Give {{HERO}} a specific fictional want, understandable emotional response or playful curiosity, plus a self-initiated action that matters. Show the protagonist contributing to the event rather than only watching and combining others\' opinions. A mistake is optional; never assign real-world personality traits to a child.',
  context.episodeIndex === 1
    ? 'Both safe choices pursue the same goal through visibly different child actions and outcomes. Make each branch promise a DISTINCT ongoing method or consequence, not merely different labels. For example, turn-taking and echo/call-and-response must stay different games in their immediate bridges and subsequent scenes; do not make both lead to an interchangeable group performance. Resolve neither choice before the child selects it; keep the preview true for both. The last planned story beat must be ONE neutral decision cue. Never put a list, rehearsal or paraphrase of the two options into the preceding story beats: the structured choice cards alone display the alternatives.'
    : 'Episode 2 begins AFTER the exact selected bridge. Treat its particular action and method as binding canon, not a theme to replace: if the child chose echo/call-and-response, preserve answering an audible call rather than swapping to everyone singing simultaneously; if turn-taking was chosen, preserve the sequential mechanism. Give at least two distinct causal beats that arise from THIS selected outcome and would not simply fit the unselected branch. Create a new child-visible consequence, finish tonight\'s established goal, and reach its small promised payoff before the calm coda. Do not repeat Episode 1\'s deliberation, reenact the bridge, invent a fresh child choice or turn the sequel into prop logistics.',
  ...(context.episodeIndex === 1 ? [
    'When generating the choice pair, test the options by stripping their labels: do they create different observable changes, discoveries or relationship consequences, or only two variants of the same singing/echo game? If equivalent, redesign the ARCHITECT blueprint before narration. Both must be kind and viable; they need not produce different moral lessons.',
    'Counterfactual pre-choice check: remove both choice cards and their bridges, then examine the planned story beats up to decision_point. If the central goal is already achieved without a selected action, revise the pre-choice beats before returning the blueprint. A reassurance, incomplete attempt, joke or encouraging conversation may happen early, but must not quietly deliver the same observable payoff promised by the options. For example, if both choices offer ways to help a quiet singer be heard in a group game, do not have the whole group already hear and successfully include that singer through a completed game before selection. Keep the goal visibly open at one neutral decision cue while preserving ordinary kindness and a warm bedtime tone; never fabricate danger or an unrelated second problem to force a choice.',
  ] : []),
  'Durable state_patch values are future-story evidence, not loose brainstorming fragments. Write last_event and relationship/canon values as concise, coherent, complete thoughts with an actual result. hero_trait should be null unless a supported lasting fictional character fact is genuinely useful; never write an unfinished phrase, truncate a clause to save tokens or infer the real child\'s personality. Preserve compact, existing canon keys whenever possible.',
  'Keep characters and species internally consistent. A vivid prop or opening obstacle should either matter later or be clearly incidental. Use an earned concrete funny, tender or surprising moment when natural to the existing scene. No required refrain, physical action quota, artificial spectacle or arbitrary grammar scoring.',
].join(' ')

export const storyNarratorEditorialGuidance = (context: NormalizedStoryContext): string => [
  'The immutable blueprint remains authoritative. Bring planned changes to life through a concrete character action, reaction, short natural dialogue and a clear image. Do not replace events with several paragraphs of planning, looking, discussing or merely changing a prop\'s position. Keep the same goal and all existing safety and identity rules.',
  ...(isNewSeriesDebut(context) ? [debutNarratorGuidance] : []),
  'For an established story, use only the existing memory, first-meeting facts and selected bridge. Do not invent or contradict a backstory merely to make a character introduction sound complete.',
  'Show an earned gentle joke or surprise through an event and character reaction, rather than announcing that something is funny. Let {{HERO}} visibly want, feel, notice or initiate only actions supported by the blueprint. Do not invent an unplanned mistake, new branch, new lore or a personality claim about the real child.',
  'Write naturally spoken, age-appropriate sentences, avoiding adult logistics. Proofread Uzbek suffixes and proper-name case endings as carefully as the rest of the prose: e.g. qo‘shiqqa instead of qo‘shiqka and Tikanning instead of Tikaning. Prefer ordinary fluent Uzbek and short direct phrases, but no blanket borrowed-word blacklist or fixed word cap. Avoid padding dialogue and repeating the same action to meet a word target.',
  context.episodeIndex === 1
    ? 'Write a complete 380-420-word story_text (hard minimum 320) BEFORE compact metadata; count only words in story_text, never choice labels, bridges or state. Develop 5-7 distinct meaningful pre-choice beats through the SAME problem. Each beat must create one observable change licensed by the immutable blueprint: a character action and reaction, a discovery, or a harmless attempt. Avoid a second round of waiting or reassurance, repetitive dialogue and unrelated actions. Do not sacrifice the story length to complete other fields. End story_text with ONE neutral, natural cue such as “Malika nima qilishini o‘yladi.” Do NOT enumerate, summarize, compare, announce or repeat the two choice actions anywhere in story_text. In particular never write Uzbek menu scaffolding “mumkin ... yoki ... mumkin”, “mumkin ... yana ... mumkin”, or Russian “можно ... или можно”; show options only in the two structured choice cards. Neither action has happened before selection. Each immediate choice bridge independently needs 30-45 meaningful words, with a concrete outcome grounded in its architect-owned resolution_goal. Do not sacrifice the story length to complete the other JSON fields.'
    : 'The selected resolution_text has already been read to the child. Keep the selected method recognizably intact in visible action: an echo game needs calls and replies, whereas turn-taking needs turns; never turn either into the other or an undifferentiated simultaneous chorus. Show the blueprint\'s distinct consequence, avoid repeating the same activity in multiple paragraphs, finish the local payoff, and reach the calm closing image. Never ask the child or {{HERO}} for another unstructured decision.',
  ...(context.episodeIndex === 1 ? [
    'Counterfactual pre-choice check: remove both choice cards and their bridges and read story_text alone up to its neutral decision cue. If the main goal has already been completed, the child decision is decorative: do not turn a tentative practice, reassurance or brief humorous moment into the full successful event before the choice. In particular, a quiet singer may be encouraged without already being heard by the entire group in the very game the two options are supposed to initiate. Respect the immutable blueprint and do not invent a new obstacle or different story goal to conceal an upstream mistake. The unresolved child-scale goal must still need one of the offered hero actions, and the first concrete result belongs in its resolution_text, not story_text.',
  ] : []),
].join(' ')
